### PR TITLE
ozipdecrypt: rework decryption logic

### PR DESCRIPTION
**Pull request by aragon12**

### CODE REVIEW

**Comment by aragon12** [comment]
@bkerler review.. and merge if u like :D

**Comment by aragon12** [comment]
well..

**Comment by bkerler** [comment]
Hi, many thanks for the addition. I will add them :)

**Comment by aragon12** [comment]
Haha yes..

i closed.. coz i thought u didn't like eet

**Comment by bkerler** [comment]
Oh, I did, but I just didn't yet have the time to add it 💃

**Comment by aragon12** [comment]
No prob.. i'll create one more PR.. merge that

**Comment by Jwaleed8** [comment]
Please Add RealMe U1 (RMX1831) ozip Extract.

**Pull request closed without merging**
